travis:
  secure:
    BINSTAR_TOKEN: DUBdQZnmy0/KHewMyVaYBUbk5b1JRB8Gn26ZhPHb1gNVKGbfHvqLzFXYGUvJvPG449nonHFu4nLZXJgg9VbSKQJfjAENO5avvSCtxNS+WSZRAhk8bpbFyMxOnAQuGp7Xg/P+q2vXmhX4lri9oOjBXJtdsfNKsNPzmUNmaijpOKZJYD5TcN/CjbUYf9jpkbF7t6FPt1kKv66425wn4b0dLxtOz9WuCIBgY8OhwI0Oe6K4DDIFia0ez3iBR+QbfaPIloKp2y/xCNgqF9nzaH88O3HPFGsi0akpYEWTuSNdYy5V3qsEujF8pYpbWy1xRB3JMFCnmIED7D5u9AjVBS+AJ8pedOY46WLCGJq5CguIm035vDkFLVZlZE6/mR0JOi2/zVL6+9fiAo97bVCRrOq0G01SKXnrkdwdlumJ3MoZ72MwWqwahfnte0B77f6KSIS6j9a6DCg9K4WZhQmcn5E7KHJ98fRdn1iHmO3ziHqR1wKnodSpE9S99QIOep+uT/sRJFfEQ4EoUP8IBATg2aoHs79nPvLbDaFFQJtd+I0aCdrxgtGOgCSpGnZsrCxN3gymc3QJf4Cs9zrPz2zGWvGu9GbAFB1/FGjL49KbvXa75rkBSnve8gNvRNjJdGJqWAjLvX014QsF6HQ/WP0LVcZbT9lTMa3dmn2Q6d1JsHyaabs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
