travis:
  secure:
    BINSTAR_TOKEN: opKEP6bhvoc8lKtE9Mf2SUOoKfOZWetYhSfQF9ixXXmhISEXHjztF4yBhlMf+wkL4+XJPy/zhBhccFMbRud8uR4jdG9xhnhGABXhCY2xiNhf4aPwHnTuLd/IgAqOXMWpRicim2kWYYulkFYwXgewmZTr8b9w1wwWE+xU7gm1ctHfoYq7fEpW9GLB7H3OIpQx2QMOUnTnyxTFZRVY5F96I2Ivo9PMsSZSGHwioS4dk4UcZYZGvGsjmmQlMbLs71P1F2ASJ2oGNoDOnuP774zG0Ctu0ULnwVOBeYvYR0rbQRv0dkZnFzyk1aGgfJ+DXADnZuw0yfL8mbuOnn3vC3iPVUmnkhy7GEYxr8d3XkKAevD9mACLc9j9jRWl2G1s9gIj3Zo21tj0X0O6KIuElKRAKXMlZ/TTMevucQZNZXZCzTT6xPj5SzV9QvqKCZjspAZFKMCM7Ce2fP2z3NSjYfQHqIQP7UR8PXgY9cZ6vsQNTbL9kGA3Kro1drqjNHoo5CbAxddpl63ekZ734JOqv5YbMlcydo9pxfTPZmWdXK5vV4a7WCQP/Y3NAmho5KIkyQlkbK5zKxlWI4xJ50BRFgC4yRaBiwnZi4J8589bFbni14Py6CaJyjhEwXoX4TqS2lFV02DE+g4fJ+qA3fHh4PWZbVMf6KdtZk+4EgRz2HC7v/A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
